### =====================================================
### Contacts API Tests
### =====================================================

@host = http://localhost:8080

### =====================================================
### Get all contacts
### =====================================================

GET {{host}}/contacts

###

### =====================================================
### Get contact by ID
### =====================================================

GET {{host}}/contacts/6a53eff75e142ac223c632b0

###


### =====================================================
### Create a new contact
### =====================================================

POST {{host}}/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "blue",
    "birthday": "1990-01-01"
}

###

### =====================================================
### Update an existing contact
### =====================================================

PUT {{host}}/contacts/6a53eff75e142ac223c632b0
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "green",
    "birthday": "1990-01-01"
}

###

### =====================================================
### Delete a contact
### =====================================================

DELETE {{host}}/contacts/6a53eff75e142ac223c632b0
